[package]
name = "MyVectorDB"
version = "0.1.0"
edition = "2024"
build = "src/build.rs"

[dependencies]
anyhow = "1.0.100"
ndarray = "0.17.2"
ort = { version =  "2.0.0-rc.11", features = ["load-dynamic", "openvino"] }
tokenizers = "0.22"
memmap2 = "0.9"

[[bin]]
name = "main"
path = "src/main.rs"